# Site settings
title: 7 Blink
motto: Efficient
email: #
description: > # this means to ignore newlines until "baseurl:"
  A simple blog for my current programming projects.  Python, Django, Java, Javascript
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.7blink.com" # the base hostname & protocol for your site

logo: /images/logo.png
logo-width: # used to set width of logo.  eg 750

twitter_username: #
github_username:  7blink
disqus: 7blink

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data"]
permalink: pretty
highlighter: rouge

paginate: 5
#if you want the blog on a different page use the line below
#paginate_path: "/blog/page:num/"

sass:
  sass_dir: _sass
  style: compressed

navbar:
  archive: true
  categories: true
  store: false
  tags: true
  about: false

rename_navbar:
  home: home
  archive: archive
  category: programming languages
  store: store
  tags: tags
  about: about

additional_pages:
  - Feedback
